### ISSUE TITLE
monethaAddress mapping is not falsifiable

### ISSUE THREAD

**Issue by dstutman** [monetha/bug-bounty#8]
https://github.com/monetha/TrustReputationSmartContracts/blob/master/contracts/Restricted.sol

Issue:
Restricted.sol does not provide a method to make a `monethaAddress` mapping false. It is unclear whether multiple `monethaAddresses` should be valid at once, though from the choice to use a map it seems so. However, there is no way to remove an address from the mapping. If there is ever a compromise of a `monethaAddress`, deployed contracts will remain vulnerable indefinitely.

Fix:
If the intent is for there to be a single valid `monethaAddress`, use an address instead of a mapping.
If the intent is for there to be multiple `monethaAddress`es, provide a method for setting addresses in the mapping to false.

Classification:
Impact: Medium - High.
Likelihood: Low

**Comment by LiudasJan** [comment]
Dear Daniel, 

Thank you for the feedback and detail description. In case you are willing to apply for Monetha's Bug Bounty Program we cannot accept it because bounty participants must follow the rules for issue submission. You can find them here: https://github.com/monetha/bug-bounty || https://www.monetha.io/bounty 

However, we've looked at the issue you described, and we can confirm that it was done by intent. We may change contract in future by your recommendations. 
Program scope and rules: https://bounty.monetha.io 

All the best,
Monetha Team
